### ISSUE TITLE
It seems a "cd n8n" is missing from the instructions

### ISSUE THREAD

**Issue by albanleandri** [that-one-tom/n8n-on-oracle-vm#1]
Hi there, thanks for the great guide. I finally made it.
I noticed two things that could be improved in the readme, it's mostly to guide hobbyists like me:

```
cd ~
mkdir n8n
cd n8n
nano docker-compose.yml
```

=> It was missing a "cd n8n" before creating the docker-compose file. Fortunately, the comment preceding the code clearly mentioned that the file had to be created inside the new folder. I wanted to report this.

Also, for the "A record", maybe you could add that the A record must be registered "where the domain names" are (in my case was Netlify), which is not necessarily the domain registrant (Bluehost, in my case). I blocked on that for a moment, and the propagation makes it all more confusing as you are not sure if you did something wrong or if there's just a delay and you have to wait. I realized the issue thanks to Bluehost customer service.

Thanks again for the great guide.

**Comment by that-one-tom** [comment]
Thanks so much for your feedback @albanleandri! I've updated the guide in https://github.com/that-one-tom/n8n-on-oracle-vm/commit/0be7690f53df7f1ec65096c89b2e9a7461d311b1.
